language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - CXX=g++-4.8

node_js:
  - v4.2

before_install:
  - npm install -g npm@2.14.7

git:
  depth: 10

branches:
  only:
    - master

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - g++-4.8
