language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 0.12

git:
  depth: 10

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - libgnome-keyring-dev
